export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const OPEN_PROGRAMS = 'OPEN_PROGRAMS';
export const OPEN_PROGRAMS_SUCCESS = 'OPEN_PROGRAMS_SUCCESS';
export const OPEN_PROGRAMS_FAILURE = 'OPEN_PROGRAMS_FAILURE';

export const PROGRAMS = 'PROGRAMS'
export const PROGRAMS_SUCCESS = 'PROGRAMS_SUCCESS'
export const PROGRAMS_FAILURE = 'PROGRAMS_FAILURE'
